apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bank-app-cd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AstralUniverse1/infra-ansible-cd.git
    targetRevision: main
    path: helm/bank-app-cd
    helm:
      releaseName: bank-app-cd
  destination:
    server: https://kubernetes.default.svc
    namespace: bank
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true